# Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server:2.1.2
    ports:
      - published: 5025
        target: 8025
      - published: 5080
        target: 8080
      - published: 5081
        target: 8081
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/fakesmtp
        target: /tmp
    environment:
      TZ: Europe/Berlin
      SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
      SPRING_MAIN_BANNER-MODE: LOG
      SPRING_LAZY-INITIALIZATION: true
      SPRING_JPA_OPEN-IN-VIEW: true
    hostname: fakesmtp
    container_name: fakesmtp
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 768M
