# Copyright (C) 2023 - present Juergen Zimmermann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ==============================================================================
# N o d e
# ==============================================================================
#node:
#  port: 3000

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

# "pg-native" erfordert die Installation von PostgreSQL: Docker-Image genügt nicht
# "oracledb" erfordert die Installation der Client-Bibliotheken von Oracle
# "better-sqlite3" erfordert Python zum Uebersetzen, wenn das Docker-Image gebaut wird

db:
  #type: postgres
  #type: mysql
  #type: sqlite

  host: postgres
  #host: mysql

  #username: film
  #password: p
  #passwordAdmin: p
  #name: film
  populate: true

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  dir: /tmp
  pretty: true
  #default: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# J W T
# ==============================================================================
# 1d = 1 Tag, 1h = 1 Stunde, 1m = 1 Minute, 1s = 1 Sekunde
#jwt:
#  expiresIn: 1h
#  issuer: https://hka.de/JuergenZimmermann

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: fakesmtp
  port: 8025
  log: false

# ==============================================================================
# Authentifizierung
# ==============================================================================
auth:
  # https://github.com/docker/compose/issues/6741: '' wegen $
  passwordEncoded: '$argon2i$v=19$m=4096,t=3,p=1$aaxA2v/9rRSPGkwYN+NQog$27Huii1XtD3iEd62fog+04G26LRPZMHoYCI6AGKTL8M'
