# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose -f compose.busybox.yml up
#           docker compose exec busybox ash
#               nslookup postgres
#           docker compose -f compose.busybox.yml down

services:
  busybox:
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'echo Container mit busybox ist gestartet! && sleep 3600'
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
