# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

services:
  film:
    image: juergenzimmermann/film:2023.10.0-wolfi
    volumes:
      - type: bind
        source: app.yml
        target: /app/dist/config/resources/app.yml
        read_only: true
      - type: bind
        source: ../../log
        target: /app/log
        read_only: true
      - type: bind
        source: ../../src/config/resources/tls/private-key.pem
        target: /app/dist/config/resources/tls/private-key.pem
        read_only: true
      - type: bind
        source: ../../src/config/resources/jwt/private-key.pem
        target: /app/dist/config/resources/jwt/private-key.pem
        read_only: true
      - type: bind
        source: ../../src/config/resources/db/sqlite/film.sqlite
        target: /app/dist/config/resources/db/sqlite/film.sqlite
